name: CI Build

on:
  push:
    branches: [ issue/gha ]
  pull_request:
    branches: [ issue/gha ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:

    - name: Check out sources
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Build with Maven
      run: ./mvnw clean dependency:list test -Dsort -B -Pjakarta-ee-10,distribute,convergence

    - name: Deploy to Artifactory
      env:
        ARTIFACTORY_USR: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PSW: ${{ secrets.ARTIFACTORY_PASSWORD }}
      run: ./mvnw -s settings.xml -B clean deploy -P-Pjakarta-ee-10,distribute,snapshot -Dmaven.test.skip=true
